### PR TITLE
Support additional attributes in initial diaper change intent utterance

### PR DESCRIPTION
**Pull request by btoconnor**
*Issue #, if available:* #6

*Description of changes:*
This change makes it so users can attach diaper change information in the initial utterance to Alexa.  For example, now someone can say "Alexa, ask Baby Buddy to record a wet diaper change", which will automatically flag this as a wet diaper (and not solid).  Four values are "supported": `wet`, `solid`, `full` (which is both wet and solid), and `empty` (which is neither).

This changeset also refactors how first names are parsed - it uses Amazon's built in [`AMAZON.FirstName`](https://developer.amazon.com/en-US/docs/alexa/custom-skills/slot-type-reference.html) slot type, which is in "Public beta".  It seems unlikely that Amazon will completely revoke the type altogether, but it states that it reserves the right to alter it based on feedback.  Considering the use case here, and the relative niche-ness of this skill, I feel this is okay, but open to discussion.

Note: this changes how we prompt for some of the "additional information" in the intent.  Previously, the skill marked "wet", "solid", "ounces" and "color" as required slot values, and if we skipped filling them in it just guessed.  This allows the code to rely on the builtin validation from the Alexa developer kit to prompt with elicitations defined in the `en-US.json` file.  Unfortunately, there's a longstanding issue where you cannot manually fill in required custom values with validation.  It is unclear if this will be changed anytime soon.  Thus - this PR moves these attributes to no longer be required, and manually prompts within the code itself (rather than relying on Alexa's built in elicitation).  Unfortunately, that removes the code from the locale specific file, but considering there's only `en-US`, and there were other prompts being manually specified in the code anyway, I felt it was a reasonable stopgap.

Based on my browsing of other Alexa skills, the "best practice" here might be to split out these additional questions into separate intents, and manage the values through a session.  This seems beyond the scope of this PR, but I think it's worth calling out in case someone comes along later on and wants to migrate the code to that structure.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cdubz** [comment]
@btoconnor testing with `ask dialog` Alexa can't seem to sort out the name for the updated diaper change command --

```
User  > Alexa, ask Baby Buddy to record a wet diaper change for Kyle
Alexa > Would you like to add more details like amount and color?
User  > No
Alexa > Please specify which child by saying, Ask Baby Buddy to record diaper change for Jack.
User  > Alexa, ask Baby Buddy to record a wet diaper change for Kyle
Alexa > Would you like to add more details like amount and color?
User  > no
Alexa > Please specify which child by saying, Ask Baby Buddy to record diaper change for Jack.
User  > Alexa, ask Baby Buddy to record a full diaper change for Kyle
Alexa > Would you like to add more details like amount and color?
User  > yes
Alexa > Was it brown, black, green, or yellow?
User  > brown
Alexa > How many ounces?
User  > 5
Alexa > Please specify which child by saying, Ask Baby Buddy to record diaper change for Jack.
```

And other attempts all seem to have trouble with the name --

```
Alexa > Please specify which child by saying, Ask Baby Buddy to record diaper change for Jack.
User  > Alexa, ask Baby Buddy to start sleeping Kyle
Alexa > Please specify which child by saying, Ask Baby Buddy to start sleeping session for Jack.
User  > Alexa, ask Baby Buddy to start sleeping for Kyle
Alexa > Please specify which child by saying, Ask Baby Buddy to start sleeping session for Jack.
User  > Alexa, ask Baby Buddy to start sleeping for Kyle Hall
Alexa > Please specify which child by saying, Ask Baby Buddy to start sleeping session for Jack.
User  > Alexa, ask Baby Buddy when was the last feeding Kyle
Alexa > Please specify which child by saying, Ask Baby Buddy when did Jack eat last.
User  > When did Kyle eat last?
Alexa > Please specify which child by saying, Ask Baby Buddy when did Jack eat last.
User  > Ask Baby Buddy when did Kyle eat last?
Alexa > Please specify which child by saying, Ask Baby Buddy when did Jack eat last.
```

**Comment by btoconnor** [comment]
Huh - that's really weird! This appears to be coming from the name matching code - this was working with the test name I was using (Junior), but when I switched to "Kyle" I started seeing the same issues.  But based on the logs, the code is correctly receiving "Kyle" in the `name` slot.

Thanks for flagging this - I'll dig in.

Some screenshots:
image

image

**Comment by btoconnor** [comment]
@cdubz nice catch - I suspect this issue was due to me using the test name "Junior" which could just as easily have been a regular word rather than a name.  With `AMAZON.FirstName`, it looks like Amazon matches the name with a capital first letter (ie "Kyle" instead of "kyle") - in the function `getSelectedChild()`, we were only lower casing the names from the API - not from the returned string from Alexa.  The latest commit lower cases the name provided to the function so it should be comparing a lower case string with another lower case string now rather than mixed strings.

This resolved the issue you ran into for me locally with the test name "Kyle".

That being said - this matching algorithm feels a little ... brittle.  What happens if someone were to name their child "Kiel", or in terms closer to me - "Bryan" - I'm not sure the matching algorithm here would be able to handle this.  

I might try to look into this - it's something [Dynamic Entities](https://developer.amazon.com/blogs/alexa/post/db4c0ed5-5a05-4037-a3a7-3fe5c29dcb65/use-dynamic-entities-to-create-personalized-voice-experiences) might be able to solve - though not sure, I just started reading about them.

**Comment by cdubz** [comment]
@btoconnor this looks good now! Sorry for the delay... 😬

**Review by cdubz — APPROVED** [review]

**Comment by btoconnor** [comment]
Not a problem! Thanks for taking a look.

BTW - I'm open to taking a look into more of the intents to provide additional information, if there are ideas.

**Pull request merged**
